### PR TITLE
Fix connection close in exporter process

### PR DESCRIPTION
**Pull request by antoninbas**
There were a couple of issues:

* ConnToCollector is exposed to the consumers of the library, and in Antrea we call ConnToCollector whenever sending a record fails. So the library itself should not call ConnToCollector as this is inherently racy. For example, it is possible for templateRefCh to be closed twice, despite the isChanClosed test (check-then-act race). We could add a mutex and a boolean, but I feel like it is better to just let consumer call ConnToCollector.
* When the exporter process is sending over UDP, there was a typo where a `break` was used instead of `return`. The `break` statement breaks from the select case, and not from the surrounding for loop, so the goroutine would never terminate.

### CODE REVIEW

**Comment by antoninbas** [comment]
@heanlan @yuntanghsu this is a bit of a disruptive change, so I hope you can provide some feedback

**Review by yuntanghsu — APPROVED** [review]
LGTM.

In the description, I think it should be CloseConnToCollector instead of ConnToCollector? I don't find the usage for ConnToCollector...

**Comment by yuntanghsu** [comment]
I think we will need to add CloseConnToCollector in the Stop() for IPFIXEXporter in antrea repo?

**Comment by antoninbas** [comment]
> I think we will need to add CloseConnToCollector in the Stop() for IPFIXEXporter in antrea repo?

Yes I think it would be better. Right now if the FA configuration is updated to remove the IPFIX exporter, we will not close the connection, which seems wrong. It's independent of the change in this PR though, but it should be addressed at some point.

**Pull request merged**
