### PR TITLE
Set VERSION to 0.2.1

### PR DESCRIPTION
**Pull request by zyiou**

### CODE REVIEW

**Review by srikartati — APPROVED** [review]

**Comment by srikartati** [comment]
Checks are not running because of no workflow.
Can you cherrypick this commit on to this PR? https://github.com/vmware/go-ipfix/commit/466b6d3faff06af3e53138d05a4dc2f5a1da66f1

We can merge them together

**Comment by zyiou** [comment]
@srikartati Sure. I have cherrypick CI commit. Do we need to change the release log?

**Comment by srikartati** [comment]
> @srikartati Sure. I have cherrypick CI commit. Do we need to change the release log?

Yes theoretically. We can skip it as this is repo related and not feature related.

**Review by srikartati — APPROVED** [review]

**Comment by srikartati** [comment]
I did rebase and merge as it is better to keep them as separate commits.

**Comment by zyiou** [comment]
Got it. Thanks!

**Pull request merged**
