### PR TITLE
changes for release v0.6.0

### PR DESCRIPTION
**Pull request by heanlan**

### CODE REVIEW

**Review by yanjunz97 — APPROVED** [review]
LGTM

**Review by antoninbas — APPROVED** [review]
I assume that once this is merged, release-0.6.0 will be in the same state as the main branch?

**Comment by heanlan** [comment]
> I assume that once this is merged, release-0.6.0 will be in the same state as the main branch?

Expect for the VERSION, yes, I believe so. I created the release-0.6.0 branch based on release-0.5.0.

**Comment by antoninbas** [comment]
> > I assume that once this is merged, release-0.6.0 will be in the same state as the main branch?
> 
> Expect for the VERSION, yes, I believe so. I created the release-0.6.0 branch based on release-0.5.0.

You may want to double check with `git diff`. Usually, for a new minor release, you want to base it off the main branch.

**Comment by heanlan** [comment]
Sorry, I just saw it. I ran `git diff`. And it seems there are some inherited typos in CHANGELOG. No other diffs.
```
diff --git a/CHANGELOG.md b/CHANGELOG.md
index 3e53a69..a625071 100644
--- a/CHANGELOG.md
+++ b/CHANGELOG.md
@@ -11,7 +11,7 @@ Changelog](https://keepachangelog.com/en/1.0.0/).
 - Refactor TLS client config for exporter. (#294, @antoninbas)
 ## 0.5.13 12-05-2022
 ### Added
-- Add APIs for custom registries. (#288, @praveingk)
+- Add APIs for custom registries. (#299, @praveingk)
 ### Changed
 - Renew fake cert for tests. (#290, @yanjunz97)
 ## 0.5.12 02-23-2022
@@ -103,7 +103,7 @@ inactive expiry timeouts. (#185, @stati)
 - Modify rule priority types in Antrea registry. (#184, #189, @heanlan)
 - Delete unrequired method of deleting record from record map witout lock. (#181, @stati)
 - Modify network policy related fields in Antrea registry. (#179, @zyiou)
-- Move klog to klog/v2. (#187, @zyiou)
+- Move klog to klog/v2. (@187, @zyiou)
 ### Fixed
 - Remove codecov token from script. (#176, @zyiou)
 ## 0.5.0 04-16-2021
diff --git a/VERSION b/VERSION
index 7dfd4ee..60f6343 100644
--- a/VERSION
+++ b/VERSION
@@ -1 +1 @@
-v0.7.0-dev
+v0.6.0
```

**Pull request merged**
