### PR TITLE
Changes for Release v0.5.2

### PR DESCRIPTION
**Pull request by heanlan**

### CODE REVIEW

**Review by srikartati — COMMENTED** [review]
wait for yiou's change: #196 ?

**Comment by heanlan** [comment]
> wait for yiou's change: #196 ?

Just asked Yiou, she said we can go ahead without her pr.

**Comment by zyiou** [comment]
we should also include klog version change in this PR

**Review by srikartati — APPROVED** [review]
LGTM

**Comment by srikartati** [comment]
Merging it.

**Pull request merged**
