### PR TITLE
Fix the image tag in kafka flow collector manifest

### PR DESCRIPTION
**Pull request by srikartati**

### CODE REVIEW

**Review by zyiou — COMMENTED** [review]
Why do we need this change? Current yaml follows the same format as yamls provided by Antrea e.g. flow-aggregator.yml in https://github.com/antrea-io/antrea/releases/tag/v0.13.4

**Comment by srikartati** [comment]
> Why do we need this change? Current yaml follows the same format as yamls provided by Antrea e.g. flow-aggregator.yml in https://github.com/antrea-io/antrea/releases/tag/v0.13.4

We are following the version tags from confluentinc here.
https://hub.docker.com/r/antrea/confluentinc-zookeeper/tags?page=1&ordering=last_updated
https://hub.docker.com/r/confluentinc/cp-zookeeper/tags?page=1&ordering=last_updated

**Review by zyiou — APPROVED** [review]
LGTM

**Comment by srikartati** [comment]
Did a rebase.. please approve again @zyiou

**Review by zyiou — APPROVED** [review]
LGTM

**Pull request merged**
