### PR TITLE
Remove conn mutex for exporting process

### PR DESCRIPTION
**Pull request by antoninbas**
Golang Conn objects are "thread-safe" and multiple goroutines may invoke methods
on a Conn simultaneously. The Golang standard library will take care of
serializing the call correctly. So we can remove this extra mutex.

### CODE REVIEW

**Comment by antoninbas** [comment]
@srikartati @zyiou for review (I don't have write access to this repo so cannot assign reviewers directly)

**Review by zyiou — APPROVED** [review]
Thanks for taking care of this issue. LGTM

**Review by srikartati — APPROVED** [review]
Thanks for fixing this. LGTM.

**Comment by srikartati** [comment]
Merging this as there are no comments to be resolved.

**Pull request merged**
